# Generated by Django 5.0.2 on 2024-06-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='item_images/null.png', null=True, upload_to='item_images'),
        ),
    ]
